print("DIGITE O SEU NOME:")
nome = input()
print("DIGITE A SUA IDADE:")
idade = input()
print ("DIGITE O SEU SEXO (M/F)")
sexo = input()
print ("DIGITE O NOME DE SUA RUA /N°:")
rua = input()
print ("DIGITE O SEU BAIRRO")
bairro = input()
print ("DIGITE A SUA CIDADE")
cidade = input()
print("------------------------------------------")
print("O SEU NOME É: " , nome)
print ("A SUA IDADE È: " , idade)
print ("O SEU SEXO É: " , sexo)
print ("O SEU ENDEREÇO É: RUA :", rua,"bairro:", bairro, "CIDADE:",cidade)